### ISSUE TITLE
Curl server denied you to change to the given directory

### ISSUE THREAD

**Issue by tylermcinnes** [nesi/training-environment-rstudio-rnaseq-app#1]
Attempting to download a reference transcriptome: 

curl ftp://ftp.ensemblgenomes.org/pub/plants/release-28/fasta/saccharomyces_cerevisiae/cdna/Saccharomyces_cerevisiae.R64-1-1.cdna.all.fa.gz -o Scerevisiae.fa.g

Result is: 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (9) Server denied you to change to the given directory

Currently working around with downloading to own machine and using Upload button from within RStudio.

**Comment by chrisdjscott** [comment]
Hi @tylermcinnes , does that curl command work for you on your local machine? If I copy that command and run it on my laptop it also fails with exactly the same error. I think the error is coming from the remote FTP server - is it possible that authentication is required and you have that cached on your local machine (assuming it works there) somehow?

**Comment by DininduSenanayake** [comment]
@tylermcinnes 

* This file is already included in the training environment RNA_seq directory (https://github.com/nesi/training-environment-rstudio-rnaseq-app/tree/main/docker/RNA_seq/Transcriptome) 
* In case you want to download your own copy, it requires `htts://`. Following works

```
curl https://ftp.ensembl.org/pub/release-112/fasta/saccharomyces_cerevisiae/cdna/Saccharomyces_cerevisiae.R64-1-1.cdna.all.fa.gz -o Saccharomyces_cerevisiae.R64-1-1.cdna.all.fa.gz
```

**Comment by tylermcinnes** [comment]
Thanks both!
